include:
  template: SAST.gitlab-ci.yml

image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: default

stages:
  - test
  - deploy

maven-deploy-kapture-client:
  image: maven:3.5.4-jdk-8-alpine
  stage: deploy
  script:
    - mvn clean deploy -Dregistry=https://maven.pkg.github.com/Kaleido-Biosciences -Dtoken=${GH_TOKEN}
  only:
    - master
